# Generated by Django 6.1 on 2026-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('retail_price', models.FloatField(help_text='USD per gallon')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('price_observations', models.IntegerField(default=1)),
                ('geocode_source', models.CharField(default='gazetteer', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='routing_fue_lat_2a0979_idx')],
            },
        ),
    ]
